services:
  - type: web
    name: arbitrage-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RPC_URL
        fromSecret: true
      - key: PRIVATE_KEY
        fromSecret: true
      - key: FLASH_LOAN_PROVIDER
        value: aave-v3
